apiVersion: v1
kind: Pod
metadata:
  name: movies 
  labels:
    app: movies
spec:
  containers:
  - name: movies
    image: astro7982/moviesjs-micro
    env:
    - name: SPLUNK_OTEL_AGENT
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://$(SPLUNK_OTEL_AGENT):4317"
    - name: OTEL_SERVICE_NAME
      value: "movies"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "deployment.environment=dev"
  restartPolicy: OnFailure  
